/*
* Description: Project 1 c file. Contains function implementations for the commands listed in command.h
*			   
*
* Author: Jared Hall
*
* Date: 09/22/2019
*
* Notes:
* 1. Do not edit this file.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include <dirent.h>
#include "command.h"


void listDir(){
    /*for the ls command*/
    // help from www.ibm.com/docs/es/zos/2.4.0
    DIR *dir;
    struct dirent *entry;

    if((dir = opendir(".")) == NULL){
        //If directory doesn't open, error
        printf("Failure to list directory contents.\n");
    } else {
        while((entry = readdir(dir)) != NULL){
            //print all contents of working directory
            printf("%s\n", entry->d_name);
        }
        closedir(dir);
    }
} 


void showCurrentDir(){
    /*for the pwd command*/
    int size = 100;
    char buf[size];
    if(getcwd(buf, size) == NULL){
        //size was too small
        printf("Failure to print working directory.\n");
    } else {
        printf("%s\n", buf);
    }


} 


void makeDir(char *dirName){
    /*for the mkdir command*/
    //Looking at documentation, 0700 allows rwx------
    if(mkdir(dirName, 0700) == 0){
        printf("Directory |%s| created.\n", dirName);
    } else {
        printf("Failure to create directory.\n");
    }
}
    

void changeDir(char *dirName){
    /*for the cd command*/
    if(chdir(dirName) == 0){
        printf("Changed directory to\n", dirName);
    } else {
        printf("Failure to change directory.\n");
    }

}


void copyFile(char *sourcePath, char *destinationPath){
    /*for the cp command*/
    printf("This the copyFile command.\n");
} 


void moveFile(char *sourcePath, char *destinationPath){
    /*for the mv command*/
    printf("This the moveFile command.\n");
} 


void deleteFile(char *filename){
    /*for the rm command*/
    if(unlink(filename) == 0){
        printf("File %s deleted\n", filename);
    } else {
        printf("Failure to delete file.\n");
    }
} 


void displayFile(char *filename){
    /*for the cat command*/
    FILE *myfile;
    size_t len = 128;
	char* line_buf = malloc (len);


    myfile = fopen (filename, "r");
        if(myfile == NULL){
            //File does not exist
            printf("File %s does not exist. Please check the file name again.\n", filename);
        }
        else {
            //File exists
            while (getline (&line_buf, &len, myfile) != -1){
                printf("%s", line_buf);
            }
            // Close file when done
            printf("\n");
            fclose(myfile);
        }
        // Free malloc line buf afterwards
        free(line_buf);
} 